import { ReactNode } from "react";
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body style={{ display: "flex" }}>
        <aside style={{ padding: 25, background: "grey" }}>
          {" "}
          <ul>
            <li>
              <Link href="/thing/1000">1000 ms delay</Link>
            </li>
            <li>
              <Link href="/thing/2000">2000 ms delay</Link>
            </li>
            <li>
              <Link href="/thing/5000">5000 ms delay</Link>
            </li>
          </ul>
        </aside>
        <main>{children}</main>
      </body>
    </html>
  );
}
